

spring: 
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/ipark?useSSL=false&allowPublicKeyRetrieval=true  
    username: root
    password: root  
    initialization-mode: always
    continue-on-error: false  
  messages: 
     basename: messages
      
  main: 
    allow-bean-definition-overriding: true
  servlet: 
    session: 
      timeout: 1800  
---     
logging: 
  level: 
    org: 
      springframework: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} -%msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} -%msg%n"
  file: application.log      
      