

spring: 
  jpa: 
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/ipark?useSSL=false&allowPublicKeyRetrieval=true  
    username: root
    password: root  
    initialization-mode: always
    continue-on-error: true  
  messages: 
     basename: messages

     
logging: 
  level: 
    org: 
      springframework: ERROR